#!/usr/bin/env bash
set -euo pipefail

REPO="wells1137/meowload-downloader"
REPO_URL="https://github.com/$REPO"

echo "============================================"
echo "  MeowLoad Downloader - 全平台发布指南"
echo "============================================"
echo ""
echo "GitHub Repo: $REPO_URL"
echo ""
echo "────────────────────────────────────────────"
echo "  第一步：获取各平台 Token（仅需一次）"
echo "────────────────────────────────────────────"
echo ""
echo "  1. ClawHub:      https://clawhub.ai → Settings → API Tokens"
echo "  2. Sundial Hub:  npx sundial-hub auth login （浏览器登录后自动获取）"
echo "  3. localskills:  npm i -g @localskills/cli && localskills login"
echo ""
echo "────────────────────────────────────────────"
echo "  第二步：将 Token 存入 GitHub Secrets"
echo "────────────────────────────────────────────"
echo ""
echo "  运行以下命令（替换 xxx 为你的实际 token）:"
echo ""
echo "  gh secret set CLAWHUB_TOKEN -R $REPO"
echo "  gh secret set SUNDIAL_TOKEN -R $REPO"
echo "  gh secret set LOCALSKILLS_TOKEN -R $REPO"
echo ""
echo "────────────────────────────────────────────"
echo "  第三步：打 Tag 触发自动发布"
echo "────────────────────────────────────────────"
echo ""
echo "  git tag v1.0.0 && git push origin v1.0.0"
echo ""
echo "  GitHub Actions 会自动发布到:"
echo "  ClawHub / Sundial Hub / localskills.sh / agentskill.sh"
echo ""
echo "────────────────────────────────────────────"
echo "  需要手动提交的平台"
echo "────────────────────────────────────────────"
echo ""
echo "  Cursor Marketplace:  https://cursor.com/marketplace/publish"
echo "  agentskill.sh:       https://agentskill.sh/submit"
echo ""
echo "────────────────────────────────────────────"
echo "  已自动生效的平台（无需任何操作）"
echo "────────────────────────────────────────────"
echo ""
echo "  skills.sh:       npx skills add $REPO"
echo "  Playbooks.com:   npx playbooks add skill $REPO"
echo "  AgentSkillsRepo: 自动索引"
echo ""
